### ISSUE TITLE
USER STORY: <A Poll Response>

### ISSUE THREAD

**Issue by ZakariyeNor** [ZakariyeNor/first-agile-project#3]
In order to **be able to add votes and keep record of all previous polls including voting details** As a **administrator**, I can **Increase levels of interactions to add poll in the home pag, to gather input or feedback such as time of running and best tracks**

**Comment by ZakariyeNor** [comment]
In order **to say may thoughts and ideas** As a **User** I can **Add comments and send**

**Comment by ZakariyeNor** [comment]
In order to **receive benefit** As a **role** I can **goal/desire**


## Acceptence Criteria

 - User write his thoughts and feedback in the **text input field**
 - User can hide name and their personal information to **click checkbox**
 - Administrator can track comments, feedback and best track votes to **use owner side**
 - Administrator can vote and list the best track vote's **in owner site**

**Comment by ZakariyeNor** [comment]
In order to **receive benefit** As a **role** I can **goal/desire**


## Acceptence Criteria

 - User write his thoughts and feedback in the text input field
 - User can hide names and their personal information
 - Administrator can track comments, feedback and best track votes 
 - Administrator can vote and list the best track vote's 

## Tasks
 
- [ ] Task 1 Design UI 
- [ ] Task 2 Create HTML, JAVASCRIPT & CSS
- [ ] Task 3 Create models
- [ ] Task 4 Test the product functionality
- [ ] Task 5 Verify the product owner with the owner

**Comment by ZakariyeNor** [comment]
This is completed
